import 'package:injectable/injectable.dart';
import '../entities/account_tag.dart';
import '../repositories/account_tags_repository.dart';

@injectable
class CreateTagUseCase {
  final AccountTagsRepository _tagsRepository;

  CreateTagUseCase(this._tagsRepository);

  Future<AccountTag> call({
    required String name,
    String? description,
    String? color,
    String? icon,
  }) async {
    final tag = AccountTag(
      id: '', // Will be generated by the repository
      name: name,
      description: description,
      color: color,
      icon: icon,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      createdBy: 'System', // This should come from user context
      isActive: true,
    );

    return await _tagsRepository.createTag(tag);
  }
}

